### ISSUE TITLE
sheetbase Server not found

### ISSUE THREAD

**Issue by contributorpw** [contributorpw/google-apps-script-awesome-list#147]
Hi @lamnhan 

I can't reach https://sheetbase.dev

```sh
183 links checked.

ERROR: 1 dead links found!
[✖] https://sheetbase.dev → Status: 0
```

Any suggestion or a replacement?

**Comment by lamnhan** [comment]
Hello there,
For the Sheetbase project, I was in the process of upgrading to the new version, but unfortunately, I ran out of budget and time, plus the pandemic. The development is currently inactive. I don't know when I will be able to work on it again.
I am sorry for the inconvenient. You can view all the current source code here: https://github.com/sheetbase
Feel free to clone and do whatever you want with them, they are all MIT licensed.
Thank you!
